import { test, expect } from "@playwright/test";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { launchMmdModoki } from "./electron-app.mjs";

const root = resolve(fileURLToPath(new URL("../..", import.meta.url)));
test.setTimeout(150000);
for (const backend of ["classic", "frameGraph"]) test(`external WGSL ${backend}: GUI apply, invalid reload, save and permission`, async ({}, testInfo) => {
    const app = await launchMmdModoki(root);
    try {
        const page = await app.app.firstWindow();
        const errors = [];
        page.on("pageerror", error => errors.push(error.message));
        page.on("console", message => { if (message.type() === "error") console.log(message.text().slice(0, 1000)); });
        await page.waitForFunction(() => Boolean(window.mmdModokiE2e));
        await page.evaluate(backend => localStorage.setItem("mmd_modoki.postEffectBackend", backend), backend);
        await page.reload(); await page.waitForFunction(() => Boolean(window.mmdModokiE2e));
        await page.evaluate(path => window.mmdModokiE2e.loadModel(path), resolve(root, "test/fixtures/external-parent/sss-reference.pmx"));
        const openSettings = async () => {
            await page.locator('[data-i18n="menu.tools"]').click();
            await page.locator('[data-menu-command="tools.experimentalSettings"]').click();
        };
        await openSettings();
        const dialog = page.locator('[data-popup-id="experimental-settings"]');
        const permission = dialog.getByLabel("外部WGSL材質を有効にする", { exact: true });
        await expect(permission).not.toBeChecked();
        await permission.check(); await expect(permission).toBeEnabled();
        await dialog.locator(".app-menu-dialog-close").click();
        await page.locator("#btn-toggle-shader-panel").click();
        await page.locator('[data-effect-tab="materials"]').click();
        const folder = testInfo.outputPath("effect"); mkdirSync(folder, { recursive: true });
        const manifestPath = resolve(folder, "effect.modoki.json");
        const sourcePath = resolve(folder, "main.wgsl");
        const originalSource = readFileSync(resolve(root, "docs/examples/external-material-effect-v1/main.wgsl"), "utf8");
        writeFileSync(manifestPath, readFileSync(resolve(root, "docs/examples/external-material-effect-v1/effect.modoki.json")));
        writeFileSync(sourcePath, originalSource);
        await app.app.evaluate(({ dialog }, file) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] }); }, manifestPath);
        await page.locator("#external-wgsl-load").click();
        await expect(page.locator("#external-wgsl-status")).toContainText("読込済み");
        await page.locator("#external-wgsl-apply-all").click();
        await expect(page.locator("#external-wgsl-apply-all")).toBeEnabled({ timeout: 25000 });
        await expect(page.locator("#external-wgsl-diagnostic")).not.toContainText("操作に失敗");
        const saved = await page.evaluate(() => window.mmdModokiE2e.exportProjectState());
        expect(saved.externalEffects).toHaveLength(1);
        expect(saved.scene.models[0].materialShaders.filter(item => item.externalEffect)).toHaveLength(2);
        await page.locator(".shader-material-item").first().click();
        await expect(page.locator("#external-wgsl-status")).toHaveAttribute("data-state", "ready");
        writeFileSync(sourcePath, originalSource.replace("return surface.color * gain;", "return missingValue;"));
        await page.locator("#external-wgsl-reload").click();
        await expect(page.locator("#external-wgsl-diagnostic")).toContainText("操作に失敗", { timeout: 25000 });
        const errorHost = page.locator("#viewport-runtime-status-host");
        const errorCard = errorHost.getByRole("alert");
        await expect(errorCard).toBeVisible();
        await expect(errorCard).toHaveAttribute("data-level", "error");
        await expect(errorCard.locator(".viewport-runtime-status__detail")).toContainText("WGSL");
        await expect(errorCard.locator(".viewport-runtime-status__detail")).toContainText("操作に失敗");
        await expect(errorCard.locator(".viewport-runtime-status__action").first()).toBeVisible();
        await page.screenshot({ path: testInfo.outputPath("wgsl-compile-error-overlay.png") });
        await errorCard.locator(".viewport-runtime-status__action--quiet").click();
        await expect(errorHost).toBeHidden();
        const afterError = await page.evaluate(() => window.mmdModokiE2e.exportProjectState());
        expect(afterError.scene.models[0].materialShaders).toEqual(saved.scene.models[0].materialShaders);
        // Package/source validation failures use the same card, before GPU compilation.
        writeFileSync(sourcePath, "var<uniform> forbidden: f32;\n" + originalSource);
        await page.locator("#external-wgsl-reload").click();
        await expect(errorCard).toBeVisible();
        await expect(errorCard.locator(".viewport-runtime-status__detail")).toContainText("WGSL");
        await expect(page.locator("#external-wgsl-diagnostic")).toContainText("main.wgsl");
        await errorCard.locator(".viewport-runtime-status__action--quiet").click();
        await expect(errorHost).toBeHidden();
        writeFileSync(sourcePath, originalSource);
        await page.locator("#external-wgsl-reload").click();
        await expect(page.locator("#external-wgsl-reload")).toBeEnabled();
        await expect(page.locator("#external-wgsl-status")).toHaveAttribute("data-state", "ready");
        await expect(errorHost).toBeHidden();
        await app.app.evaluate(({ dialog }) => { dialog.showOpenDialog = async () => ({ canceled: true, filePaths: [] }); });
        await page.locator("#external-wgsl-load").click();
        await expect(page.locator("#external-wgsl-load")).toBeEnabled();
        await expect(errorHost).toBeHidden();
        await page.locator('[data-wgsl-parameter="Strength"]').fill("0.7");
        await page.locator('[data-wgsl-parameter="Strength"]').press("Tab");
        await expect(page.locator("#external-wgsl-load")).toBeEnabled();
        await expect(page.locator('[data-wgsl-parameter="Strength"]')).toHaveValue("0.7");
        const projectPath = testInfo.outputPath("wgsl.mmdproj");
        await app.app.evaluate(({ dialog }, file) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: file }); }, projectPath);
        await page.locator('[data-i18n="menu.file"]').click();
        await page.locator('[data-menu-command="file.saveProject"]').click();
        await expect.poll(() => { try { return JSON.parse(readFileSync(projectPath, "utf8")).externalEffects?.length; } catch { return 0; } }).toBe(1);
        expect(JSON.parse(readFileSync(projectPath, "utf8")).externalEffects[0].path).toContain(".assets/effects/");
        await openSettings(); await permission.uncheck(); await expect(permission).toBeEnabled();
        await dialog.locator(".app-menu-dialog-close").click();
        await expect(page.locator("#external-wgsl-status")).toHaveAttribute("data-state", "disabled");
        await page.locator("#external-wgsl-clear").click(); await expect(page.locator("#external-wgsl-load")).toBeDisabled();
        await expect.poll(async () => (await page.evaluate(() => window.mmdModokiE2e.exportProjectState())).scene.models[0].materialShaders.filter(item => item.externalEffect).length).toBe(1);
        await app.app.evaluate(({ dialog }, file) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] }); }, projectPath);
        await page.locator('[data-i18n="menu.file"]').click();
        await page.locator('[data-menu-command="file.loadProject"]').click();
        await expect.poll(async () => (await page.evaluate(() => window.mmdModokiE2e.exportProjectState())).scene.models[0]?.materialShaders?.filter(item => item.externalEffect).length ?? 0).toBe(2);
        await openSettings(); await permission.check(); await expect(permission).toBeEnabled();
        await dialog.locator(".app-menu-dialog-close").click();
        await expect(page.locator("#external-wgsl-status")).toHaveAttribute("data-state", "ready");
        await expect(page.locator('[data-wgsl-parameter="Strength"]')).toHaveValue("0.7");
        // A different uniform layout on one material must coexist with the original on another.
        const expanded = JSON.parse(readFileSync(manifestPath, "utf8"));
        expanded.parameters.Extra = { type: "vec4f", default: [0, 0, 0, 1] };
        writeFileSync(manifestPath, JSON.stringify(expanded));
        await page.locator("#external-wgsl-reload").click();
        await expect(page.locator("#external-wgsl-reload")).toBeEnabled();
        const expandedState = await page.evaluate(() => window.mmdModokiE2e.exportProjectState());
        expect(expandedState.externalEffects).toHaveLength(2);
        // Mode banks retain the external assignment and do not copy it to PBR.
        await openSettings();
        await dialog.getByLabel("PBRモード", { exact: true }).check();
        await expect(dialog.getByLabel("PBRモード", { exact: true })).toBeEnabled({ timeout: 25000 });
        const pbr = await page.evaluate(() => window.mmdModokiE2e.exportProjectState());
        expect(pbr.scene.models[0].materialShaders.every(item => !item.externalEffect)).toBe(true);
        expect(pbr.scene.models[0].materialSettingsByMode["mmd-standard"].materials.some(item => item.externalEffect)).toBe(true);
        await dialog.locator(".app-menu-dialog-close").click();
        await page.keyboard.press("Control+Z");
        await expect.poll(async () => (await page.evaluate(() => window.mmdModokiE2e.exportProjectState())).externalEffects?.length).toBe(1);
        await openSettings();
        await dialog.getByLabel("PBRモード", { exact: true }).uncheck();
        await expect(dialog.getByLabel("PBRモード", { exact: true })).toBeEnabled({ timeout: 25000 });
        await dialog.locator(".app-menu-dialog-close").click();
        await expect(page.locator("#external-wgsl-status")).toHaveAttribute("data-state", "ready");
        await expect(page.locator('[data-wgsl-parameter="Strength"]')).toHaveValue("0.7");
        await page.locator("#external-wgsl-clear").click(); await expect(page.locator("#external-wgsl-load")).toBeEnabled();
        expect((await page.evaluate(() => window.mmdModokiE2e.exportProjectState())).scene.models[0].materialShaders.filter(item => item.externalEffect)).toHaveLength(1);
        await page.keyboard.press("Control+Z");
        await expect(page.locator("#external-wgsl-status")).toHaveAttribute("data-state", "ready");
        const capture = testInfo.outputPath("capture"); mkdirSync(capture, { recursive: true });
        await page.evaluate(folder => window.mmdModokiE2e.captureSinglePngSurfaceToPath(folder, 640, 360), capture);
        expect((await page.evaluate(() => window.mmdModokiE2e.getWebGpuValidationDiagnostics())).messages).toEqual([]);
        await page.screenshot({ path: testInfo.outputPath("external-wgsl.png") });
        await page.evaluate(path => window.mmdModokiE2e.loadModel(path), resolve(root, "test/fixtures/external-parent/sss-reference.pmx"));
        const twoModels = await page.evaluate(() => window.mmdModokiE2e.exportProjectState());
        expect(twoModels.scene.models).toHaveLength(2);
        expect(twoModels.scene.models[0].materialShaders.filter(item => item.externalEffect)).toHaveLength(2);
        expect((twoModels.scene.models[1].materialShaders ?? []).some(item => item.externalEffect)).toBe(false);
        expect(errors).toEqual([]);
    } finally { await app.close(); }
});
