import { test, expect } from "@playwright/test";
import { resolve, join } from "node:path";
import { randomUUID } from "node:crypto";
import { launchMmdModoki, selectCenterBone } from "./electron-app.mjs";
import { enableMcpEditing } from "./mcp-client.mjs";

const root = resolve(import.meta.dirname, "../..");
for (const pbr of [false, true]) test(`MCP key ranges and GUI clipboard, paste, move, delete (${pbr ? "PBR" : "normal"})`, async () => {
    test.setTimeout(240000);
    const launched = await launchMmdModoki(root);
    try {
        const page = await launched.app.firstWindow();
        await page.waitForFunction(() => Boolean(window.mmdModokiE2e));
        const rpc = await enableMcpEditing(page);
        const context = async () => (await rpc("mmd_get_context")).structuredContent;
        const query = async (name, extra = {}) => (await rpc(name, { target: (await context()).target, ...extra })).structuredContent;
        const request = async (name, extra) => {
            const current = await context();
            const input = { target: current.target, expectedEditRevision: current.editRevision, operationId: randomUUID(), ...extra };
            return { input, response: await rpc(name, input) };
        };
        const edit = async (name, extra) => {
            const result = await request(name, extra);
            expect(result.response.isError, JSON.stringify(result.response)).not.toBe(true);
            return { input: result.input, data: result.response.structuredContent };
        };
        const complete = async operation => {
            const job = await edit("mmd_start_ui_operation", { operation });
            let result;
            await expect.poll(async () => {
                result = (await rpc("mmd_get_operation", { target: job.input.target, operationId: job.input.operationId })).structuredContent;
                return result.status;
            }, { timeout: 120000 }).not.toBe("running");
            expect(result.status, JSON.stringify(result)).toBe("completed");
        };
        await complete({ kind: "materialMode", pbr });
        await page.evaluate(async path => { await window.mmdModokiE2e.loadModel(path); await window.mmdModokiE2e.loadModel(path); }, resolve(root, "test/fixtures/external-parent/tofu.pmx"));
        const modelInstanceId = (await context()).models[0].instanceId;
        const scope = { kind: "model", modelInstanceId };
        await edit("mmd_select_timeline", { scope });
        await selectCenterBone(page);
        const keys = async () => (await query("mmd_inspect", { kind: "keyframes" })).items;
        const center = (await query("mmd_inspect", { kind: "tracks" })).items.find(track => track.name === "センター");
        await edit("mmd_register_keyframes", { scope, tracks: [{ category: center.category, name: center.name }], collision: "replace" });
        const initial = (await keys()).find(key => key.name === "センター" && key.frame === 0);
        const track = { category: initial.category, name: initial.name };
        const set = (frame, x) => ({ action: "set", track, frame, payload: { ...initial.payload, positions: [x, 0, 0] } });
        await edit("mmd_edit_keyframes", { scope, collision: "replace", operations: [set(10, 1), set(20, 2)] });
        const select = (startFrame, endFrame) => edit("mmd_select_keyframes", { scope, selection: { kind: "range", startFrame, endFrame, tracks: [track] } });
        await select(10, 20);
        const selection = await query("mmd_get_keyframe_selection", { limit: 1 });
        expect(selection.totalCount).toBe(2);
        expect(selection.items[0].frame).toBe(10);
        expect((await query("mmd_get_keyframe_selection", { offset: 1, limit: 1, expectedEditRevision: selection.editRevision })).items[0].frame).toBe(20);
        await expect(page.locator("#btn-kf-copy")).toBeEnabled();
        const copied = await edit("mmd_copy_keyframes", { scope });
        expect(copied.data.control.keyCount).toBe(2);
        await expect(page.locator("#btn-kf-paste")).toBeEnabled();
        const originalClipboard = await query("mmd_get_keyframe_clipboard", { limit: 1 });
        expect(originalClipboard.items[0].payload.positions[0]).toBe(1);
        expect((await query("mmd_get_keyframe_clipboard", { offset: 1, expectedClipboardId: originalClipboard.clipboardId })).items[0].frameOffset).toBe(10);
        await edit("mmd_edit_keyframes", { scope, collision: "replace", operations: [set(10, 99)] });
        expect((await query("mmd_get_keyframe_clipboard")).items[0].payload.positions[0]).toBe(1);
        await select(10, 20);
        // Human copy updates the exact same clipboard observed by MCP.
        await page.locator("#btn-kf-copy").click();
        const clipboard = await query("mmd_get_keyframe_clipboard");
        expect(clipboard.clipboardId).not.toBe(originalClipboard.clipboardId);
        expect(clipboard.items[0].payload.positions[0]).toBe(99);
        const secondScope = { kind: "model", modelInstanceId: (await context()).models[1].instanceId };
        await edit("mmd_select_timeline", { scope: secondScope });
        const transferred = await edit("mmd_paste_keyframes", { scope: secondScope, clipboardId: clipboard.clipboardId, frame: 5, collision: "reject" });
        expect((await keys()).find(key => key.frame === 5 && key.name === track.name).payload.positions[0]).toBe(99);
        await edit("mmd_undo", { editId: transferred.data.editId });
        expect((await keys()).some(key => key.frame === 5)).toBe(false);
        await edit("mmd_select_timeline", { scope });
        const pasteArgs = { scope, clipboardId: clipboard.clipboardId, frame: 40, collision: "reject" };
        const stale = await request("mmd_paste_keyframes", { ...pasteArgs, clipboardId: originalClipboard.clipboardId });
        expect(stale.response.structuredContent.error.code).toBe("CLIPBOARD_CHANGED");
        const collision = await request("mmd_paste_keyframes", { ...pasteArgs, frame: 20, dryRun: true });
        expect(collision.response.structuredContent.error.code).toBe("KEY_COLLISION");
        const dryRun = await edit("mmd_paste_keyframes", { ...pasteArgs, dryRun: true });
        expect(dryRun.data.plan.changedKeyCount).toBe(2);
        expect((await keys()).some(key => key.frame === 40)).toBe(false);
        const pasted = await edit("mmd_paste_keyframes", pasteArgs);
        const at = async frame => (await keys()).find(key => key.name === track.name && key.frame === frame);
        expect((await at(40)).payload.positions[0]).toBe(99);
        expect((await at(50)).payload.positions[0]).toBe(2);
        await edit("mmd_undo", { editId: pasted.data.editId });
        expect(await at(40)).toBeUndefined();
        await edit("mmd_redo", { editId: pasted.data.editId });
        // MCP copy can be pasted through the real GUI button too.
        await select(40, 50);
        await edit("mmd_copy_keyframes", { scope });
        await edit("mmd_select_keyframes", { scope, selection: { kind: "clear" } });
        await edit("mmd_set_playback", { action: "seek", frame: 80 });
        await page.locator("#btn-kf-paste").click();
        expect((await at(80)).payload.positions[0]).toBe(99);
        expect((await at(90)).payload.positions[0]).toBe(2);
        await select(80, 90);
        const moved = await edit("mmd_edit_keyframe_selection", { scope, operation: { action: "move", frameOffset: 10 }, collision: "reject" });
        expect(await at(80)).toBeUndefined();
        expect((await at(90)).payload.positions[0]).toBe(99);
        expect((await at(100)).payload.positions[0]).toBe(2);
        await edit("mmd_undo", { editId: moved.data.editId });
        expect((await at(80)).payload.positions[0]).toBe(99);
        await select(80, 90);
        const deletionArgs = { scope, operation: { action: "delete" }, collision: "reject" };
        await edit("mmd_edit_keyframe_selection", { ...deletionArgs, dryRun: true });
        expect(await at(80)).toBeTruthy();
        const deleted = await edit("mmd_edit_keyframe_selection", deletionArgs);
        expect(await at(80)).toBeUndefined();
        await edit("mmd_undo", { editId: deleted.data.editId });
        const filePath = join(launched.tempDir, "clipboard.mmdproj");
        await complete({ kind: "saveProject", filePath, overwrite: false });
        await complete({ kind: "loadProject", filePath });
        await edit("mmd_select_timeline", { scope });
        await edit("mmd_set_playback", { action: "seek", frame: 80 });
        await selectCenterBone(page);
        await expect.poll(async () => Number(await page.locator("#bone-controls input[data-control-key='tx']").inputValue())).toBeCloseTo(99);
        expect((await at(90)).payload.positions[0]).toBe(2);
        await edit("mmd_select_keyframes", { scope, selection: { kind: "keys", keys: [{ track, frame: 80 }] } });
        await page.locator("#btn-kf-copy").click();
        const singleClipboard = await query("mmd_get_keyframe_clipboard");
        expect(singleClipboard.totalCount).toBe(1);
        expect(singleClipboard.items[0].frameOffset).toBe(0);
        expect(singleClipboard.items[0].payload.positions[0]).toBe(99);
    } finally { await launched.close(); }
});
